services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "${DATABASE_USERNAME}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: "${DATABASE_NAME}"
    ports:
      - "5432:5432"

  # redis:
  #   image: redis:7-alpine
  #   expose:
  #     - 6379
